services:
  frontend:
    build:
      context: ./client # Path to your client folder
      dockerfile: Dockerfile
    ports:
      - '80:80' # Map host port 80 to container port 80 (Nginx)
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./server # Path to your server folder
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Map host port 8080 to container port 8080 (Node.js)
    env_file:
      - ./server/.env
    volumes:
      - ./server/public/app/assets/uploads:/usr/src/app/public/app/assets/uploads
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
